const en = {
  meta: { title: 'Global C&B | Your future and dreams start here' },

  ui: {
    audiences: ['Students & Parents', 'Agencies & Overseas Partners', 'Universities & Schools', 'Companies & Employers'],
    search: 'Search',
    searchPlaceholder: 'What are you looking for? (e.g. language course, referral, agency)',
    noResult: 'No results. Request a consultation and we will guide you directly.',
    menu: 'Menu',
    close: 'Close',
    home: 'Home',
    nav: ['My Counseling · Partners', 'About Us', 'Korean · Pre-departure', 'D-4 Language Study', 'D-2 Degree Programs', 'Career · Startup · Settle', 'News · Share'],
    more: 'Learn more',
    consultNow: 'Free consultation',
    next: 'Next step',
    prev: 'Previous step',
    language: 'Language',
    comingSoon: 'Coming soon',
    comingSoonCta: 'Get notified · consult',
  },

  menu: [
    { route: 'consult', links: [['form', '1:1 course consultation'], ['portals', 'Platform login'], ['referral', 'Student referral program'], ['share-link', 'Create referral / promo link'], ['sales', 'Staff promotion & sales kit'], ['partners', 'B2B agency partners'], ['institutions', 'University & company partnership']] },
    { route: 'about', links: [['mission', 'About Global C&B'], ['platform', 'CRM · LMS platform'], ['values', 'Our values']] },
    { route: 'pre-departure', links: [['courses', '48·80·200-hour courses'], ['compare', 'Course comparison'], ['course-finder', 'Find my course']] },
    { route: 'd4', links: [['overview', 'Language study overview'], ['steps', 'Process'], ['support', 'Our support']] },
    { route: 'd2', links: [['overview', 'Degree overview'], ['steps', 'Process'], ['support', 'Our support']] },
    { route: 'career', links: [['overview', 'Career overview'], ['steps', 'Process'], ['support', 'Our support']] },
    { route: 'news', links: [['notice', 'News & admissions'], ['faq', 'FAQ']] },
  ],

  hero: {
    badge: 'GLOBAL C&B',
    title1: 'Your future and dreams,',
    title2: 'start right here.',
    desc: 'Pre-departure Korean, language training and university admission. We prepare your next step together, matched to your level and goals.',
    ctaConsult: 'Find the right course for me',
    ctaCompare: 'Compare 48·80·200 hours',
    chips: ['Level-based pre-departure training', 'University & career counseling'],
    cardTitle: 'Your partner in planning the future',
    cardSub: 'Education · Admission · Career counseling',
  },

  home: {
    audienceTitle: 'Who is Global C&B for?',
    audienceDesc: 'Students, agencies, universities and companies each use the services they need on one platform.',
    audiences: [
      { title: 'Students & Parents', desc: 'A 1:1 roadmap from pre-departure study to university and jobs', route: 'pre-departure' },
      { title: 'Agencies & Overseas Partners', desc: 'Student registration, progress tracking and transparent commissions', route: 'consult/partners' },
      { title: 'Universities & Schools', desc: 'Verified applicants with learning records, plus outsourced training', route: 'consult/institutions' },
      { title: 'Companies & Employers', desc: 'International graduates with verified Korean and majors', route: 'consult/institutions' },
    ],
    pathTitle: 'From pre-departure to settlement: a 4-step journey',
    pathDesc: 'Education and counseling at every stage flow seamlessly through our CRM and LMS.',
    path: [
      { step: '01', title: 'Korean · Pre-departure', desc: 'Level-based 48·80·200-hour courses and arrival preparation', route: 'pre-departure' },
      { step: '02', title: 'D-4 Language Study', desc: 'Language institute admission, visa, settling in, attendance', route: 'd4' },
      { step: '03', title: 'D-2 Degree Programs', desc: 'Data-driven university matching and admission support', route: 'd2' },
      { step: '04', title: 'Career · Startup · Settle', desc: 'Internships, jobs, startups and long-term settlement', route: 'career' },
    ],
    growTitle: 'Share together, grow together',
    growDesc: 'Every contribution — students who refer, staff who promote, agencies who send students — is recorded accurately on the platform.',
    grow: [
      { title: 'Student referral', desc: 'Refer a friend and both get course benefits', route: 'consult/referral' },
      { title: 'Staff promotion · sales', desc: 'Personal links, promo kits, performance dashboard', route: 'consult/sales' },
      { title: 'B2B agencies', desc: 'Partner portal, co-branded courses, settlements', route: 'consult/partners' },
    ],
    ctaTitle: 'Find your next step today',
    ctaDesc: 'Get a course, admission and career roadmap with a free level test and 1:1 consultation.',
  },

  pages: {
    consult: { eyebrow: 'MY COUNSELING · PARTNERS', title: 'My Counseling · Partners', desc: 'Start everything here: student consultations, referral and promo links, and agency, university or company partnerships.' },
    about: { eyebrow: 'ABOUT GLOBAL C&B', title: 'About Us', desc: 'Global C&B is a student journey platform connecting Campus and Career.' },
    'pre-departure': { eyebrow: 'KOREAN · PRE-DEPARTURE', title: 'Korean · Pre-departure', desc: 'Get ahead on your first language-institute term and university admission with level-based Korean before you arrive.' },
    news: { eyebrow: 'NEWS · SHARE', title: 'News · Share', desc: 'Check intake schedules, course openings and partner sessions — and share them with friends.' },
  },

  courses: {
    eyebrow: 'PRE-DEPARTURE COURSES',
    title: '48 · 80 · 200 hours of level-based pre-departure training',
    desc: 'Every course records level tests, attendance and achievement in the LMS, and learning reports are shared with your counselor.',
    hoursUnit: 'hrs',
    recommended: 'Popular',
    targetLabel: 'For',
    goalLabel: 'Learning goal',
    outcomeLabel: 'Outcome',
    items: [
      {
        hours: 48, name: 'Starter', tagline: 'From Hangul to everyday Korean', period: 'About 4–6 weeks · online LIVE + VOD',
        target: 'Complete beginners or students who can only read Hangul',
        goal: 'Read and write Hangul, introduce yourself, essential phrases for arrival and daily life',
        modules: ['Hangul letters & pronunciation', 'Survival Korean (airport, housing, bank)', 'Basic laws & etiquette for daily life', 'Arrival orientation'],
        outcome: 'Ready for language-institute Level 1',
      },
      {
        hours: 80, name: 'Basic', tagline: 'Start your first term with confidence', period: 'About 8–10 weeks · LIVE classes + homework feedback',
        target: 'Students about to start language study (D-4)',
        goal: 'TOPIK I Level 1 vocabulary and grammar, adapting to classes in Korean',
        modules: ['800 core words & grammar', 'Listening & speaking focus', 'Intro to TOPIK I question types', 'Korean culture & campus life'],
        outcome: 'Aim for TOPIK I Level 1 · higher class placement',
        highlight: true,
      },
      {
        hours: 200, name: 'Intensive', tagline: 'Shorten language study and head to university', period: 'About 16–20 weeks · small-group LIVE + 1:1 coaching',
        target: 'Students aiming for fast degree admission (D-2) or scholarships',
        goal: 'TOPIK I Level 2 or higher, basic academic Korean',
        modules: ['Complete beginner grammar', 'TOPIK I mock exams', 'Academic Korean & presentations', 'Admission counseling & documents'],
        outcome: 'Aim for TOPIK I Level 2 · admission counseling',
      },
    ],
    compareTitle: 'Course comparison',
    compareHead: 'Item',
    compareRows: [
      ['Total study hours', '48 hrs', '80 hrs', '200 hrs'],
      ['Level test (start · finish)', '○', '○', '○'],
      ['LIVE classes', '2× / week', '3× / week', '4–5× / week'],
      ['Homework & pronunciation feedback', '-', '○', '○ (1:1)'],
      ['TOPIK mock exams', '-', '1', '3'],
      ['Learning report → counselor', '○', '○', '○'],
      ['University & career counseling', 'Basic', 'Basic', 'Advanced'],
    ],
    finder: {
      title: 'Find my course',
      desc: 'Answer 3 questions and we will recommend a course. The result is added to your consultation form automatically.',
      questions: [
        { q: 'What is your current Korean level?', options: ['Brand new / I only know Hangul', 'I can greet and introduce myself', 'Around TOPIK Level 1'] },
        { q: 'What is your first goal in Korea?', options: ['Learn Korean step by step at a language institute', 'Language study, then university', 'Enter a degree program as soon as possible'] },
        { q: 'How long until you arrive in Korea?', options: ['Within 2 months', '2–4 months', 'More than 4 months'] },
      ],
      resultLabel: 'Recommended course',
      resultDesc: 'Your counselor confirms the final placement after a free level test.',
      cta: 'Request consultation for this course',
      levelTest: 'Take the free level test',
      restart: 'Start over',
    },
  },

  stages: {
    factsLabel: 'Key facts',
    stepsLabel: 'Process',
    supportLabel: 'How Global C&B supports you',
    disclaimer: 'Visa requirements may change according to the latest rules of the Korea Immigration Service (HiKorea). We re-check the current rules with you during counseling.',
    items: {
      d4: {
        eyebrow: 'STEP 02 · D-4',
        title: 'D-4 Language Study',
        summary: 'In this stage you complete a regular Korean program at a university language institute. We support you from application documents, financial proof and visa to settling in, attendance and grades.',
        steps: [
          ['Level test · counseling', 'Institute and term recommendations for your level and goals'],
          ['Apply to an institute', 'Application, academic records and financial documents'],
          ['Visa · arrival', 'Apply for the D-4 visa after the certificate of admission, arrival orientation'],
          ['Settle in · study', 'Alien registration, bank and housing; attendance and grade management'],
        ],
        support: ['Matching with university language institutes · application guidance', 'Financial proof and D-4 visa checklist', 'Airport pickup, housing, alien registration, bank and SIM guide', 'Attendance and grades tracked in the LMS to prevent visa risks', 'Guidance on part-time work permission requirements'],
        facts: [['Terms', 'Usually 4 terms a year, about 10 weeks each'], ['Goal for university', 'TOPIK Level 3+ (varies by university and major)'], ['Recommended prep', '80- or 200-hour pre-departure course']],
      },
      d2: {
        eyebrow: 'STEP 03 · D-2',
        title: 'D-2 Bachelor’s & Graduate Programs',
        summary: 'Based on your LMS data and TOPIK score, we recommend universities and majors you can apply to and support you through admission documents and the change to D-2 status.',
        steps: [
          ['Admission diagnosis', 'University/major report based on TOPIK, grades and interests'],
          ['Application prep', 'Personal statement and study plan editing, interview practice'],
          ['Admission · status', 'Apply for a D-2 visa or change from D-4 to D-2 after acceptance'],
          ['Academic management', 'Credit and graduation requirement coaching each semester'],
        ],
        support: ['University/major recommendation report based on grades and interests', 'Personal statement and study plan editing, interview prep', 'Scholarships, dormitories and IEQAS-certified universities', 'Documents for changing status from D-4 to D-2', 'Coaching on credits and graduation requirements (e.g. TOPIK 4)'],
        facts: [['Programs', 'Bachelor’s (D-2-2) · Master’s (D-2-3) · Doctoral (D-2-4)'], ['Language requirement', 'Usually TOPIK 3+; many universities require Level 4 to graduate'], ['Intakes', 'March and September (varies by university)']],
      },
      career: {
        eyebrow: 'STEP 04 · CAREER',
        title: 'Career · Startup · Settlement',
        summary: 'We design your path after graduation: job seeking, employment at Korean companies, startups and settling in a region — connected to our partner companies’ talent pool.',
        steps: [
          ['Career planning', 'Counseling based on major, language and preferred region'],
          ['Build skills', 'Résumé, cover letter and interview coaching, workplace Korean'],
          ['Matching · hiring', 'Internships and jobs at partner companies, visa guidance'],
          ['Settle · start up', 'Long-term settlement programs, startup education and networks'],
        ],
        support: ['Career paths: job seeking (D-10), professional (E-7), regional (F-2-R)', 'Internship and job matching with partner companies, résumé and interview coaching', 'Technology startup (D-8-4) and startup education programs', 'Long-term settlement prep such as the KIIP integration program', 'Network for startups and jobs back home after returning'],
        facts: [['Connections', 'Partner company talent pool · local government settlement programs'], ['Training', 'Workplace Korean · business etiquette'], ['Rules', 'Latest HiKorea notices']],
      },
    },
  },

  platform: {
    eyebrow: 'CRM × LMS PLATFORM',
    title: 'Counseling (CRM) and learning (LMS) work as one',
    desc: 'Who referred you and what you have learned come together in one student profile — the basis for recommending your next step.',
    flow: [
      ['INFLOW', 'Referral · staff · agency · SNS', 'Every inquiry from a link with a referral code or UTM is recorded with its source.'],
      ['CRM', 'Lead capture · auto-assign', 'Inquiries are assigned to counselors by country, language and course, with full history.'],
      ['LMS', 'Level test · courses', 'Level test results recommend a course; attendance and achievement are recorded.'],
      ['SYNC', 'Learning data → counseling', 'Learning reports flow back to the CRM to support admission, scholarship and visa advice.'],
      ['MATCH', 'Universities · companies', 'Students with verified learning records are recommended to universities and partner companies.'],
    ],
    crmTitle: 'CRM · Counseling management',
    crmFeatures: ['Leads by source (referrer · staff · agency · campaign)', 'Auto-assignment by country and language, counseling timeline', 'Pipelines and deadline alerts for documents, visas and admission', 'Data for referral rewards and partner commissions', 'Notifications via KakaoTalk, Zalo, WhatsApp and email'],
    lmsTitle: 'LMS · Learning management',
    lmsFeatures: ['Online level test and automatic course recommendation', '48·80·200-hour LIVE/VOD courses, attendance and homework', 'Learning reports shared with students, parents, agencies and counselors', 'TOPIK mock exams and achievement dashboard', 'Orientation on basic laws, etiquette and campus life'],
  },

  portals: {
    eyebrow: 'PLATFORM LOGIN',
    title: 'Go to your platform',
    desc: 'The same student data, shown in the right view for your role.',
    items: [
      { key: 'lms', title: 'Student & Parent LMS', desc: 'Level test, courses, learning reports, my referral link', cta: 'LMS login' },
      { key: 'partner', title: 'Agency Partner Portal', desc: 'Student registration and status, reports, commissions', cta: 'Partner login' },
      { key: 'staff', title: 'Staff CRM', desc: 'Lead assignment, counseling history, promotion dashboard', cta: 'Staff login' },
      { key: 'institution', title: 'University & Company Portal', desc: 'Recommended student profiles, training status, hiring', cta: 'Institution login' },
    ],
  },

  referral: {
    eyebrow: 'STUDENT REFERRAL',
    title: 'Start with a friend and share the benefits',
    desc: 'Current students, alumni and parents can all become referrers. Referrals are recorded automatically in the CRM so no reward is missed.',
    steps: [
      ['Get your referral link', 'Get a personal link from your LMS page or the link builder below.'],
      ['Share with friends', 'Share on KakaoTalk, Zalo, Facebook or Telegram — the referral is kept for 30 days.'],
      ['Track progress', 'See your friend’s consultation and enrollment status on your page.'],
      ['Both get rewards', 'Once enrolled, you and your friend both receive tuition discounts, books or points.'],
    ],
    note: 'Benefits and conditions follow the current seasonal promotion notice.',
  },

  sales: {
    eyebrow: 'STAFF SALES KIT',
    title: 'Staff promotion & sales — with visible results',
    desc: 'Fairs, info sessions or social media: wherever you promote, your personal code tracks everything from first click to enrollment.',
    tools: [
      ['Personal link · QR', 'Links with your staff code count every inquiry toward your performance.'],
      ['Multilingual promo kit', 'Card news, brochures and video in 6 languages, always the latest version.'],
      ['Lead pipeline', 'See your students’ progress: counseling → level test → enrollment → arrival.'],
      ['Performance dashboard', 'Conversion by channel, progress toward goals and incentive data in real time.'],
    ],
  },

  linkGen: {
    title: 'Create a referral / promo link',
    desc: 'Enter your code to instantly create a tracking link and QR code. Inquiries from this link are recorded in the CRM with their source.',
    roleLabel: 'I am a',
    roles: { ref: 'Student / parent referrer', staff: 'Global C&B staff', partner: 'Agency / overseas partner' },
    codeLabel: 'My code',
    codePh: 'e.g. MINH2026, ST-KIM01, VN-HANOI',
    channelLabel: 'Channel',
    channels: { kakao: 'KakaoTalk', zalo: 'Zalo', facebook: 'Facebook', telegram: 'Telegram', instagram: 'Instagram', offline: 'Offline · QR' },
    campaignLabel: 'Campaign (optional)',
    campaignPh: 'e.g. 2027-spring-fair',
    result: 'My link',
    copy: 'Copy',
    copied: 'Copied',
    share: 'Share',
    downloadQr: 'Save QR',
    empty: 'Enter a code to create your link.',
    shareText: 'Let’s prepare to study in Korea together with Global C&B!',
  },

  partners: {
    eyebrow: 'B2B AGENCY PARTNERS',
    title: 'Growing the study-abroad market with agencies and overseas partners',
    desc: 'Partners recruit students; Global C&B manages education, admission and settlement. All progress and settlement data is shared transparently on the platform.',
    benefits: [
      ['Partner-only portal', 'Register students in bulk and see document, visa and admission status in real time.'],
      ['Outsourced pre-departure training', 'Run 48·80·200-hour courses under a co-brand and receive learning reports.'],
      ['Transparent commissions', 'Enrollments from your partner code are counted in the CRM and settled monthly.'],
      ['University network', 'Priority access to partner universities’ admission guides, scholarships and schedules.'],
      ['Counselor training', 'Regular webinars on visa and admission rule changes and counseling know-how.'],
      ['Joint local fairs', 'Co-host study fairs in Vietnam, Uzbekistan, Mongolia, China and more.'],
    ],
    stepsTitle: 'Partner onboarding',
    steps: ['Apply', 'Agreement · partner code', 'Portal · training onboarding', 'Register · manage students', 'Monthly settlement'],
    cta: 'Apply to partner',
  },

  institutions: {
    eyebrow: 'UNIVERSITY · COMPANY',
    title: 'Partnering with universities and companies',
    desc: 'We connect international students verified by learning data with universities and companies.',
    items: [
      { title: 'Universities & Schools', desc: 'Receive applicants with verified LMS records and levels, and outsource pre-enrollment Korean and orientation.', points: ['Verified applicant pool (attendance, achievement, TOPIK)', 'Outsourced pre-enrollment Korean and orientation', 'Dropout prevention reports', 'Joint overseas recruitment sessions'], cta: 'University partnership' },
      { title: 'Companies & Employers', desc: 'Connect with international talent with verified Korean and majors for internships and jobs, plus Korean training for employees.', points: ['Talent pool by major and language', 'Internship and hiring support with visa guidance', 'Korean and job training for foreign employees', 'Local talent for overseas expansion'], cta: 'Company partnership' },
    ],
  },

  about: {
    missionTitle: 'From Campus to Career, we connect each person’s journey',
    mission: [
      'Students and families preparing to study in Korea must make decisions amid information that differs by country, school and visa type. To close this information gap, Global C&B designed pre-departure training, language study, degree admission, and employment and settlement as one journey.',
      'By linking counseling records (CRM) and learning records (LMS) into one student profile, we help students, parents, agencies, universities and companies make trustworthy decisions from the same data.',
    ],
    stats: [['6', ' languages', 'Multilingual counseling'], ['4', ' stages', 'Pre-departure → settlement'], ['3', ' courses', '48·80·200 hours'], ['1', ' platform', 'CRM + LMS integrated']],
    valuesTitle: 'Our values',
    values: [['Closing the information gap', 'Transparent guidance on visas, admission and daily life based on verified sources.'], ['Data-driven counseling', 'We recommend your next step from learning data, not guesswork.'], ['With you to the end', 'One team from pre-departure training to employment and settlement.']],
  },

  news: {
    noticeTitle: 'News & admissions',
    share: 'Share',
    copied: 'Link copied',
    items: [
      { tag: 'Admission', date: '2026.10', title: 'Consultations open for March 2027 language study (D-4)', body: 'We are now taking consultations for spring 2027 university language institutes. We recommend starting 4–6 months before arrival to allow time for documents.' },
      { tag: 'Course', date: '2026.10', title: '80-hour Basic pre-departure Korean starts LIVE in November', body: 'The 80-hour Basic course for students preparing for their first institute term opens in November. Classes are assigned after a free level test.' },
      { tag: 'Partners', date: '2026.09', title: 'Online session for overseas agencies (Vietnam · Uzbekistan · Mongolia)', body: 'Learn how to use the partner portal, co-branded training and settlement rules. The schedule is sent after you apply.' },
      { tag: 'Career', date: '2026.09', title: 'Hiring program with partner companies for graduating students', body: 'We match internships and jobs at partner companies to your major and Korean level, with résumé and interview coaching.' },
    ],
    faqTitle: 'Frequently asked questions',
    faqs: [
      ['How do I choose between the 48, 80 and 200-hour courses?', 'Your counselor recommends one based on a free level test, your arrival date and goals. You can check first with “Find my course”.'],
      ['How is a referral code applied?', 'When you open a referral link, the code is saved for 30 days and recorded in the CRM with your application. Without a link, type the code into the form.'],
      ['Can agencies see their students’ progress?', 'Yes. The partner portal shows each student’s counseling, documents, level test, courses and admission in real time, with downloadable reports.'],
      ['Which rules do visa requirements follow?', 'We follow the latest rules of the Korea Immigration Service (HiKorea). Since they change often, your counselor re-checks before you apply.'],
      ['Which languages are available for counseling?', 'Korean, English, Vietnamese, Chinese, Uzbek and Mongolian.'],
    ],
  },

  consult: {
    eyebrow: 'FREE COUNSELING',
    title: 'Free consultation · Partner application',
    desc: 'Your request goes straight into our CRM, and a counselor who speaks your language will contact you within 1 business day.',
    typeLabel: 'I am a',
    types: { student: 'Student · Parent', partner: 'Agency · Partner', university: 'University · School', company: 'Company · Employer' },
    name: 'Name',
    org: 'Organization / company',
    country: 'Country',
    countries: ['Vietnam', 'Uzbekistan', 'Mongolia', 'China', 'Nepal', 'Indonesia', 'Korea', 'Other'],
    phone: 'Phone / messenger ID',
    email: 'Email',
    contactPref: 'Preferred contact',
    contactPrefs: ['Phone', 'KakaoTalk', 'Zalo', 'WhatsApp', 'Telegram', 'Email'],
    interest: 'Interest',
    interests: { student: ['Pre-departure Korean 48 hrs', 'Pre-departure Korean 80 hrs', 'Pre-departure Korean 200 hrs', 'D-4 language study', 'D-2 degree programs', 'Career · startup · settlement'], partner: ['Partnership agreement', 'Outsourced pre-departure training', 'Student registration & management', 'Local fairs'], university: ['Student recommendation', 'Pre-enrollment training', 'Recruitment sessions'], company: ['Hiring international students', 'Internships', 'Korean training for employees'] },
    message: 'Message',
    messagePh: 'Tell us your Korean level, when you plan to arrive and any questions.',
    refCode: 'Referral / staff / partner code (optional)',
    refApplied: 'Referral code applied',
    consent: 'I agree to the collection and use of my personal data (name, contact, country) for counseling. It will be kept and deleted according to applicable law.',
    submit: 'Request consultation',
    sending: 'Sending…',
    success: 'Your request has been received. A counselor will contact you soon.',
    error: 'Something went wrong. Please try again later or contact us by email.',
    required: 'Please fill in the required fields.',
    again: 'New request',
    sideTitle: 'Contact us directly',
    sideEmail: 'Email us',
    sideKakao: 'KakaoTalk channel',
    sideLevel: 'Free level test',
    sideHours: 'Hours: Mon–Fri 09:00–18:00 (KST)',
  },

  footer: {
    desc: 'From pre-departure Korean to language study, degree programs, careers and settlement — a student journey platform connected by CRM and LMS.',
    rights: 'All rights reserved.',
  },
}

export default en
