const uz = {
  meta: { title: 'Global C&B | Kelajagingiz va orzularingiz shu yerdan boshlanadi' },

  ui: {
    audiences: ['Talabalar · Ota-onalar', 'Agentliklar · Xorijiy hamkorlar', 'Universitetlar · Taʼlim muassasalari', 'Kompaniyalar · Korxonalar'],
    search: 'Qidiruv',
    searchPlaceholder: 'Nimani qidiryapsiz? (masalan: til kursi, tavsiya, agentlik)',
    noResult: 'Natija topilmadi. Maslahatga yozilsangiz, sizga bevosita tushuntiramiz.',
    menu: 'Menyu',
    close: 'Yopish',
    home: 'Bosh sahifa',
    nav: ['Maslahat · Hamkorlar', 'Biz haqimizda', 'Koreys tili · Kelishdan oldin', 'D-4 Til kursi', 'D-2 Bakalavr · Magistratura', 'Ish · Startap · Yashash', 'Yangiliklar'],
    more: 'Batafsil',
    consultNow: 'Bepul maslahat',
    next: 'Keyingi bosqich',
    prev: 'Oldingi bosqich',
    language: 'Til',
  },

  menu: [
    { route: 'consult', links: [['form', '1:1 kurs maslahatiga yozilish'], ['portals', 'Platformaga kirish'], ['referral', 'Doʻstni tavsiya qilish dasturi'], ['share-link', 'Tavsiya · reklama havolasi yaratish'], ['sales', 'Xodimlar uchun reklama · savdo'], ['partners', 'B2B agentlik hamkorligi'], ['institutions', 'Universitet · kompaniya hamkorligi']] },
    { route: 'about', links: [['mission', 'Global C&B haqida'], ['platform', 'CRM · LMS platformasi'], ['values', 'Asosiy qadriyatlar']] },
    { route: 'pre-departure', links: [['courses', '48·80·200 soatlik kurslar'], ['compare', 'Kurslarni solishtirish'], ['course-finder', 'Menga mos kursni topish']] },
    { route: 'd4', links: [['overview', 'Til kursi haqida'], ['steps', 'Jarayon'], ['support', 'Yordam']] },
    { route: 'd2', links: [['overview', 'Bakalavr · magistratura haqida'], ['steps', 'Jarayon'], ['support', 'Yordam']] },
    { route: 'career', links: [['overview', 'Ish · yashash haqida'], ['steps', 'Jarayon'], ['support', 'Yordam']] },
    { route: 'news', links: [['notice', 'Eʼlonlar · Qabul'], ['faq', 'Koʻp beriladigan savollar']] },
  ],

  hero: {
    badge: 'GLOBAL C&B',
    title1: 'Kelajagingiz va orzularingiz',
    title2: 'shu yerdan boshlanadi.',
    desc: 'Kelishdan oldingi koreys tili, til kursi va universitetga kirish. Darajangiz va maqsadingizga mos keyingi qadamni birga tayyorlaymiz.',
    ctaConsult: 'Menga mos kurs boʻyicha maslahat',
    ctaCompare: '48·80·200 soatni solishtirish',
    chips: ['Darajaga mos tayyorgarlik', 'Universitet · kasb maslahati'],
    cardTitle: 'Kelajagingizni rejalashtirishdagi hamroh',
    cardSub: 'Taʼlim · Oʻqishga kirish · Kasb maslahati',
  },

  home: {
    audienceTitle: 'Global C&B kimlar uchun?',
    audienceDesc: 'Talabalar, agentliklar, universitetlar va kompaniyalar bitta platformada kerakli xizmatlardan foydalanadi.',
    audiences: [
      { title: 'Talabalar · Ota-onalar', desc: 'Kelishdan oldingi oʻqishdan universitet va ishgacha 1:1 yoʻl xaritasi', route: 'pre-departure' },
      { title: 'Agentliklar · Xorijiy hamkorlar', desc: 'Talabalarni roʻyxatga olish, kuzatish va shaffof komissiya', route: 'consult/partners' },
      { title: 'Universitetlar · Taʼlim muassasalari', desc: 'Oʻqish tarixi tasdiqlangan abituriyentlar va taʼlim xizmati', route: 'consult/institutions' },
      { title: 'Kompaniyalar · Korxonalar', desc: 'Koreys tili va mutaxassisligi tasdiqlangan iqtidorlar', route: 'consult/institutions' },
    ],
    pathTitle: 'Kelishdan oldin yashab qolishgacha: 4 bosqichli yoʻl',
    pathDesc: 'Har bosqichdagi taʼlim va maslahat CRM va LMS orqali uzluksiz bogʻlanadi.',
    path: [
      { step: '01', title: 'Koreys tili · Kelishdan oldin', desc: '48·80·200 soatlik kurslar va kelishga tayyorgarlik', route: 'pre-departure' },
      { step: '02', title: 'D-4 Til kursi', desc: 'Til markaziga kirish, viza, joylashish, davomat', route: 'd4' },
      { step: '03', title: 'D-2 Bakalavr · Magistratura', desc: 'Maʼlumotlarga asoslangan universitet tanlovi', route: 'd2' },
      { step: '04', title: 'Ish · Startap · Yashash', desc: 'Amaliyot, ishga joylashish, startap va uzoq muddat yashash', route: 'career' },
    ],
    growTitle: 'Birga tarqatamiz, birga oʻsamiz',
    growDesc: 'Tavsiya qilgan talaba, reklama qilgan xodim va talaba yuborgan agentlik hissasi platformada aniq qayd etiladi.',
    grow: [
      { title: 'Talaba tavsiyasi', desc: 'Doʻstingizni tavsiya qiling — ikkovingiz ham imtiyoz olasiz', route: 'consult/referral' },
      { title: 'Xodim reklamasi · savdo', desc: 'Shaxsiy havola, reklama toʻplami, natijalar paneli', route: 'consult/sales' },
      { title: 'B2B agentliklar', desc: 'Hamkor portali, qoʻshma brend kurslar, hisob-kitob', route: 'consult/partners' },
    ],
    ctaTitle: 'Bugunoq oʻzingizga mos keyingi qadamni aniqlang',
    ctaDesc: 'Bepul daraja testi va 1:1 maslahat orqali kurs, oʻqish va kasb yoʻl xaritasini oling.',
  },

  pages: {
    consult: { eyebrow: 'MY COUNSELING · PARTNERS', title: 'Maslahat · Hamkorlar', desc: 'Talaba maslahati, tavsiya va reklama havolalari, agentlik, universitet va kompaniya hamkorligi — hammasi shu yerdan boshlanadi.' },
    about: { eyebrow: 'ABOUT GLOBAL C&B', title: 'Biz haqimizda', desc: 'Global C&B — Taʼlim (Campus) va Kasb (Career)ni bogʻlovchi xalqaro talabalar platformasi.' },
    'pre-departure': { eyebrow: 'KOREAN · PRE-DEPARTURE', title: 'Koreys tili · Kelishdan oldin', desc: 'Kelishdan oldin darajangizga mos koreys tilini oʻrganib, birinchi semestrga ishonch bilan kiring va universitetga tezroq oʻting.' },
    news: { eyebrow: 'NEWS · SHARE', title: 'Yangiliklar · Ulashish', desc: 'Qabul jadvali, kurslar ochilishi va hamkorlar uchrashuvlari haqida bilib oling va doʻstlaringizga ulashing.' },
  },

  courses: {
    eyebrow: 'PRE-DEPARTURE COURSES',
    title: '48 · 80 · 200 soat: darajaga mos tayyorgarlik',
    desc: 'Barcha kurslarda daraja testi, davomat va natijalar LMSda qayd etiladi, oʻqish hisobotlari maslahatchingizga yuboriladi.',
    hoursUnit: 'soat',
    recommended: 'Tavsiya',
    targetLabel: 'Kimlar uchun',
    goalLabel: 'Oʻquv maqsadi',
    outcomeLabel: 'Natija',
    items: [
      {
        hours: 48, name: 'Starter', tagline: 'Hangul alifbosidan kundalik koreys tiligacha', period: 'Taxminan 4–6 hafta · onlayn LIVE + VOD',
        target: 'Koreys tilini yangi boshlayotgan yoki faqat Hangul oʻqiy oladiganlar',
        goal: 'Hangulda oʻqish-yozish, oʻzini tanishtirish, kelish va kundalik hayot iboralari',
        modules: ['Hangul harflari va talaffuz', 'Kundalik koreys tili (aeroport, uy-joy, bank)', 'Asosiy qonunlar va odob', 'Kelishdan oldingi yoʻriqnoma'],
        outcome: 'Til markazining 1-darajasiga tayyor',
      },
      {
        hours: 80, name: 'Basic', tagline: 'Birinchi semestrni ishonch bilan boshlang', period: 'Taxminan 8–10 hafta · LIVE darslar + uy vazifasi tahlili',
        target: 'Til kursiga (D-4) kirishga tayyorlanayotgan talabalar',
        goal: 'TOPIK I 1-daraja soʻz boyligi va grammatikasi, koreyscha darslarga moslashish',
        modules: ['800 ta asosiy soʻz va grammatika', 'Tinglash · gapirishga eʼtibor', 'TOPIK I savol turlari bilan tanishuv', 'Koreya madaniyati · kampus hayoti'],
        outcome: 'Maqsad TOPIK I 1-daraja · yuqoriroq guruhga joylashish',
        highlight: true,
      },
      {
        hours: 200, name: 'Intensive', tagline: 'Til kursini qisqartirib, universitetga', period: 'Taxminan 16–20 hafta · kichik guruh LIVE + 1:1 murabbiylik',
        target: 'Bakalavriatga (D-2) tez kirish yoki grant olishni maqsad qilganlar',
        goal: 'TOPIK I 2-daraja va undan yuqori, akademik koreys tili asoslari',
        modules: ['Boshlangʻich grammatikani yakunlash', 'TOPIK I sinov imtihonlari', 'Akademik koreys tili · taqdimot', 'Oʻqishga kirish maslahati · hujjatlar'],
        outcome: 'Maqsad TOPIK I 2-daraja · oʻqishga kirish maslahati',
      },
    ],
    compareTitle: 'Kurslarni solishtirish',
    compareHead: 'Boʻlim',
    compareRows: [
      ['Umumiy oʻquv soatlari', '48 soat', '80 soat', '200 soat'],
      ['Daraja testi (boshida · oxirida)', '○', '○', '○'],
      ['LIVE darslar', 'Haftada 2 marta', 'Haftada 3 marta', 'Haftada 4–5 marta'],
      ['Uy vazifasi · talaffuz tahlili', '-', '○', '○ (1:1)'],
      ['TOPIK sinov imtihoni', '-', '1 marta', '3 marta'],
      ['Oʻqish hisoboti → maslahatchi', '○', '○', '○'],
      ['Universitet · kasb maslahati', 'Asosiy', 'Asosiy', 'Chuqur'],
    ],
    finder: {
      title: 'Menga mos kursni topish',
      desc: '3 ta savolga javob bering — sizga kurs tavsiya qilamiz. Natija maslahat arizasiga avtomatik qoʻshiladi.',
      questions: [
        { q: 'Hozirgi koreys tili darajangiz qanday?', options: ['Yangi boshlayapman / faqat Hangulni bilaman', 'Salomlashish va oʻzimni tanishtira olaman', 'Taxminan TOPIK 1-daraja'] },
        { q: 'Koreyadagi birinchi maqsadingiz?', options: ['Til markazida bosqichma-bosqich oʻrganish', 'Til kursidan keyin universitet', 'Imkon qadar tez bakalavr · magistraturaga kirish'] },
        { q: 'Koreyaga kelishingizga qancha vaqt qoldi?', options: ['2 oydan kam', '2–4 oy', '4 oydan koʻp'] },
      ],
      resultLabel: 'Tavsiya etilgan kurs',
      resultDesc: 'Yakuniy guruh bepul daraja testidan soʻng maslahatchi tomonidan tasdiqlanadi.',
      cta: 'Ushbu kurs boʻyicha maslahat',
      levelTest: 'Bepul daraja testini topshirish',
      restart: 'Qaytadan',
    },
  },

  stages: {
    factsLabel: 'Asosiy maʼlumot',
    stepsLabel: 'Jarayon',
    supportLabel: 'Global C&B yordami',
    disclaimer: 'Viza talablari Koreya Immigratsiya xizmati (HiKorea) ning soʻnggi qoidalariga koʻra oʻzgarishi mumkin. Maslahat paytida amaldagi qoidalarni qayta tekshiramiz.',
    items: {
      d4: {
        eyebrow: 'STEP 02 · D-4',
        title: 'D-4 Til kursi',
        summary: 'Universitet qoshidagi til markazida rasmiy koreys tili dasturini oʻqish bosqichi. Hujjatlar, moliyaviy kafolat va vizadan tortib joylashish, davomat va baholargacha yoningizdamiz.',
        steps: [
          ['Daraja testi · maslahat', 'Darajangiz va maqsadingizga mos til markazi va semestr tavsiyasi'],
          ['Arizani topshirish', 'Ariza, taʼlim hujjatlari va moliyaviy kafolat'],
          ['Viza · kelish', 'Qabul guvohnomasidan keyin D-4 vizasi, kelish yoʻriqnomasi'],
          ['Joylashish · oʻqish', 'Chet ellik roʻyxati, bank, uy-joy; davomat va baholar nazorati'],
        ],
        support: ['Universitet til markazlari bilan bogʻlash · hujjatlar boʻyicha yoʻriqnoma', 'Moliyaviy kafolat va D-4 vizasi roʻyxati', 'Aeroportdan kutib olish, uy-joy, roʻyxatdan oʻtish, bank, SIM boʻyicha qoʻllanma', 'Viza xavfining oldini olish uchun davomat va baholar LMSda nazorat qilinadi', 'Qisman ishlash ruxsati shartlari haqida maʼlumot'],
        facts: [['Semestrlar', 'Odatda yiliga 4 semestr, har biri taxminan 10 hafta'], ['Universitet uchun maqsad', 'TOPIK 3-daraja va yuqori (universitet va yoʻnalishga qarab)'], ['Tavsiya etilgan tayyorgarlik', '80 yoki 200 soatlik kurs']],
      },
      d2: {
        eyebrow: 'STEP 03 · D-2',
        title: 'D-2 Bakalavr · Magistratura',
        summary: 'LMS oʻqish maʼlumotlari va TOPIK natijasi asosida mos universitet va yoʻnalishlarni tavsiya qilamiz, qabul hujjatlari va D-2 maqomiga oʻtishda yordam beramiz.',
        steps: [
          ['Oʻqishga kirish tahlili', 'TOPIK, baholar va qiziqishga koʻra universitet hisoboti'],
          ['Ariza tayyorlash', 'Motivatsion xat va oʻquv rejasini tahrirlash, intervyuga tayyorlov'],
          ['Qabul · maqom', 'Qabuldan soʻng D-2 vizasi yoki D-4 dan D-2 ga oʻtish'],
          ['Oʻqishni boshqarish', 'Har semestr kreditlar va bitirish talablari boʻyicha murabbiylik'],
        ],
        support: ['Baholar va qiziqishga koʻra universitet/yoʻnalish hisoboti', 'Motivatsion xat, oʻquv rejasi, intervyuga tayyorlov', 'Grantlar, yotoqxona, IEQAS sertifikatli universitetlar', 'D-4 → D-2 maqomini oʻzgartirish hujjatlari', 'Kreditlar va bitirish talablari (masalan, TOPIK 4) boʻyicha murabbiylik'],
        facts: [['Dasturlar', 'Bakalavr (D-2-2) · Magistr (D-2-3) · Doktorantura (D-2-4)'], ['Til talabi', 'Odatda TOPIK 3+; koʻp universitetlar bitirishda 4-darajani talab qiladi'], ['Qabul vaqti', 'Mart va sentyabr semestrlari (universitetga qarab)']],
      },
      career: {
        eyebrow: 'STEP 04 · CAREER',
        title: 'Ish · Startap · Yashash',
        summary: 'Bitirgandan keyingi yoʻlingizni rejalashtiramiz: ish izlash, Koreya kompaniyalarida ishlash, startap va hududda yashab qolish — hamkor kompaniyalar iqtidorlar bazasi bilan bogʻlanadi.',
        steps: [
          ['Kasb rejasi', 'Mutaxassislik, til va hududga koʻra maslahat'],
          ['Koʻnikmalarni tayyorlash', 'Rezyume, xat va intervyu murabbiyligi, ish joyidagi koreys tili'],
          ['Moslash · ishga olish', 'Hamkor kompaniyalarda amaliyot va ish, viza boʻyicha maʼlumot'],
          ['Yashash · startap', 'Uzoq muddat yashash dasturlari, startap taʼlimi va tarmoq'],
        ],
        support: ['Ish izlash (D-10), mutaxassis (E-7), hududiy (F-2-R) yoʻllari', 'Hamkor kompaniyalarda amaliyot va ish, rezyume va intervyu murabbiyligi', 'Texnologik startap (D-8-4) va startap taʼlimi dasturlari', 'KIIP integratsiya dasturi kabi uzoq muddat yashashga tayyorgarlik', 'Vatanga qaytgach startap va ish tarmogʻi'],
        facts: [['Aloqalar', 'Hamkor kompaniyalar bazasi · mahalliy hokimiyat dasturlari'], ['Taʼlim', 'Ish joyidagi koreys tili · biznes odobi'], ['Qoidalar', 'HiKorea soʻnggi eʼlonlari asosida']],
      },
    },
  },

  platform: {
    eyebrow: 'CRM × LMS PLATFORM',
    title: 'Maslahat (CRM) va oʻqish (LMS) yagona tizimda',
    desc: 'Sizni kim tavsiya qilgani va nimani qanchalik oʻrganganingiz bitta talaba profilida jamlanadi — bu keyingi qadamni tavsiya qilish asosidir.',
    flow: [
      ['KIRISH', 'Tavsiya · xodim · agentlik · SNS', 'Tavsiya kodi yoki UTM bilan kelgan har bir murojaat manbasi bilan qayd etiladi.'],
      ['CRM', 'Qayd etish · avtomatik taqsimlash', 'Davlat, til va kursga koʻra maslahatchiga biriktiriladi, tarix saqlanadi.'],
      ['LMS', 'Daraja testi · oʻqish', 'Test natijasiga koʻra kurs tavsiya etiladi, davomat va natijalar qayd etiladi.'],
      ['SYNC', 'Oʻqish maʼlumoti → maslahat', 'Oʻqish hisobotlari CRMga qaytib, oʻqish, grant va viza maslahatiga asos boʻladi.'],
      ['MATCH', 'Universitet · kompaniya', 'Oʻqish tarixi tasdiqlangan talabalar universitet va kompaniyalarga tavsiya etiladi.'],
    ],
    crmTitle: 'CRM · Maslahat boshqaruvi',
    crmFeatures: ['Manba boʻyicha murojaatlar (tavsiyachi · xodim · agentlik · kampaniya)', 'Davlat va tilga koʻra avtomatik biriktirish, maslahat tarixi', 'Hujjat, viza va qabul bosqichlari hamda muddat eslatmalari', 'Tavsiya mukofoti va hamkor komissiyasi uchun maʼlumotlar', 'KakaoTalk, Zalo, WhatsApp, Telegram va email bildirishnomalari'],
    lmsTitle: 'LMS · Oʻqish boshqaruvi',
    lmsFeatures: ['Onlayn daraja testi va kursni avtomatik tavsiya qilish', '48·80·200 soatlik LIVE · VOD kurslar, davomat va vazifalar', 'Oʻqish hisobotlari talaba, ota-ona, agentlik va maslahatchiga', 'TOPIK sinov imtihonlari va natijalar paneli', 'Asosiy qonunlar, odob va kampus hayoti boʻyicha yoʻriqnoma'],
  },

  portals: {
    eyebrow: 'PLATFORM LOGIN',
    title: 'Rolingiz boʻyicha platformaga kirish',
    desc: 'Bir xil talaba maʼlumotlari — rolingizga mos koʻrinishda.',
    items: [
      { key: 'lms', title: 'Talaba · Ota-ona LMS', desc: 'Daraja testi, kurslar, hisobotlar, mening tavsiya havolam', cta: 'LMSga kirish' },
      { key: 'partner', title: 'Agentlik hamkor portali', desc: 'Talabalarni roʻyxatga olish, holat, hisobotlar, komissiya', cta: 'Hamkor kirishi' },
      { key: 'staff', title: 'Xodim CRM', desc: 'Murojaatlarni taqsimlash, maslahat tarixi, natijalar paneli', cta: 'Xodim kirishi' },
      { key: 'institution', title: 'Universitet · Kompaniya portali', desc: 'Tavsiya etilgan talabalar, taʼlim holati, ishga olish', cta: 'Tashkilot kirishi' },
    ],
  },

  referral: {
    eyebrow: 'STUDENT REFERRAL',
    title: 'Doʻstingiz bilan boshlang — imtiyozlar ham birga',
    desc: 'Oʻquvchilar, bitiruvchilar va ota-onalar tavsiyachi boʻlishi mumkin. Tavsiyalar CRMga avtomatik yoziladi, hech bir mukofot unutilmaydi.',
    steps: [
      ['Tavsiya havolasini oling', 'LMS sahifangizda yoki quyidagi vosita orqali shaxsiy havola oling.'],
      ['Doʻstlarga ulashing', 'KakaoTalk, Telegram, Facebook va boshqalarda ulashing — tavsiya 30 kun saqlanadi.'],
      ['Jarayonni kuzating', 'Doʻstingizning maslahat va roʻyxatdan oʻtish holatini sahifangizda koʻring.'],
      ['Birga imtiyoz oling', 'Roʻyxatdan oʻtish tasdiqlansa, ikkovingiz ham chegirma, kitob yoki ball olasiz.'],
    ],
    note: 'Imtiyozlar va shartlar mavsumiy aksiya eʼlonlariga muvofiq.',
  },

  sales: {
    eyebrow: 'STAFF SALES KIT',
    title: 'Xodimlar reklamasi va savdosi — natija koʻrinib turadi',
    desc: 'Koʻrgazma, taqdimot yoki ijtimoiy tarmoq — qayerda reklama qilsangiz ham, shaxsiy kodingiz kirishdan roʻyxatdan oʻtishgacha kuzatadi.',
    tools: [
      ['Shaxsiy havola · QR', 'Xodim kodi bilan havoladan kelgan har bir murojaat sizning natijangizga yoziladi.'],
      ['Koʻp tilli reklama toʻplami', '6 tilda karta-yangiliklar, broshyura va videolar — doim eng soʻnggi versiya.'],
      ['Murojaatlar oqimi', 'Talabalaringiz jarayonini bitta oynada koʻring: maslahat → test → roʻyxat → kelish.'],
      ['Natijalar paneli', 'Kanallar boʻyicha konversiya, maqsad bajarilishi va bonus asoslari real vaqtda.'],
    ],
  },

  linkGen: {
    title: 'Tavsiya · reklama havolasini yaratish',
    desc: 'Kodingizni kiriting — kuzatuv havolasi va QR kod darhol yaratiladi. Bu havola orqali kelgan murojaatlar CRMga manbasi bilan yoziladi.',
    roleLabel: 'Men',
    roles: { ref: 'Talaba · ota-ona tavsiyachi', staff: 'Global C&B xodimi', partner: 'Agentlik · xorijiy hamkor' },
    codeLabel: 'Mening kodim',
    codePh: 'masalan: AZIZ2026, ST-KIM01, UZ-TASHKENT',
    channelLabel: 'Ulashish kanali',
    channels: { kakao: 'KakaoTalk', zalo: 'Zalo', facebook: 'Facebook', telegram: 'Telegram', instagram: 'Instagram', offline: 'Oflayn · QR' },
    campaignLabel: 'Kampaniya nomi (ixtiyoriy)',
    campaignPh: 'masalan: 2027-spring-fair',
    result: 'Mening havolam',
    copy: 'Nusxa olish',
    copied: 'Nusxa olindi',
    share: 'Ulashish',
    downloadQr: 'QRni saqlash',
    empty: 'Havola yaratish uchun kodni kiriting.',
    shareText: 'Global C&B bilan Koreyada oʻqishga birga tayyorlanamiz!',
  },

  partners: {
    eyebrow: 'B2B AGENCY PARTNERS',
    title: 'Agentliklar va xorijiy hamkorlar bilan birga oʻsamiz',
    desc: 'Talabalarni hamkor jalb qiladi, taʼlim, qabul va joylashishni Global C&B boshqaradi. Barcha jarayon va hisob-kitob maʼlumotlari platformada shaffof.',
    benefits: [
      ['Hamkorlar uchun portal', 'Talabalarni ommaviy roʻyxatga oling, hujjat, viza va qabul holatini real vaqtda koʻring.'],
      ['Kelishdan oldingi taʼlimni topshirish', '48·80·200 soatlik kurslarni qoʻshma brendda yuriting va hisobotlarni oling.'],
      ['Shaffof komissiya', 'Hamkor kodi orqali kelgan talabalar CRMda avtomatik hisoblanib, oylik toʻlanadi.'],
      ['Universitetlar tarmogʻi', 'Hamkor universitetlarning qabul qoidalari, grantlari va jadvallari birinchi boʻlib.'],
      ['Maslahatchilar uchun trening', 'Viza va qabul qoidalari oʻzgarishlari boʻyicha muntazam vebinarlar.'],
      ['Qoʻshma koʻrgazmalar', 'Vyetnam, Oʻzbekiston, Moʻgʻuliston, Xitoy va boshqa joylarda taʼlim koʻrgazmalari.'],
    ],
    stepsTitle: 'Hamkor boʻlish tartibi',
    steps: ['Ariza', 'Shartnoma · kod berish', 'Portal · trening', 'Talabalarni roʻyxat · boshqaruv', 'Oylik hisob-kitob'],
    cta: 'Hamkorlikka ariza',
  },

  institutions: {
    eyebrow: 'UNIVERSITY · COMPANY',
    title: 'Universitet va kompaniyalar bilan hamkorlik',
    desc: 'Oʻqish maʼlumotlari bilan tasdiqlangan xalqaro talabalarni universitet va kompaniyalar bilan bogʻlaymiz.',
    items: [
      { title: 'Universitetlar · Taʼlim muassasalari', desc: 'LMSda oʻqish tarixi va darajasi tasdiqlangan talabalarni qabul qiling, qabulgacha koreys tili va moslashuv taʼlimini topshiring.', points: ['Tasdiqlangan abituriyentlar bazasi (davomat · natija · TOPIK)', 'Qabulgacha koreys tili va yoʻriqnoma', 'Oʻqishni tashlab ketishning oldini olish hisobotlari', 'Xorijda qoʻshma qabul taqdimotlari'], cta: 'Universitet hamkorligi' },
      { title: 'Kompaniyalar · Korxonalar', desc: 'Koreys tili va mutaxassisligi tasdiqlangan xalqaro iqtidorlarni amaliyot va ishga bogʻlang, xodimlar uchun koreys tili taʼlimi.', points: ['Mutaxassislik va til boʻyicha iqtidorlar bazasi', 'Amaliyot · ishga olish va viza maʼlumoti', 'Chet ellik xodimlar uchun koreys tili va kasbiy taʼlim', 'Xorijga chiqish uchun mahalliy kadrlar'], cta: 'Kompaniya hamkorligi' },
    ],
  },

  about: {
    missionTitle: 'Taʼlim (Campus)dan Kasb (Career)gacha — har bir insonning yoʻlini bogʻlaymiz',
    mission: [
      'Koreyada oʻqishga tayyorlanayotgan talabalar va oilalar davlat, maktab va viza turiga qarab turlicha boʻlgan maʼlumotlar orasida qaror qabul qilishi kerak. Bu maʼlumot boʻshligʻini qisqartirish uchun Global C&B kelishdan oldingi taʼlim, til kursi, bakalavr va magistraturaga kirish, ish va yashab qolishni yagona yoʻl sifatida loyihalashtirdi.',
      'Maslahat yozuvlari (CRM) va oʻqish yozuvlari (LMS)ni bitta talaba profiliga bogʻlab, talabalar, ota-onalar, agentliklar, universitetlar va kompaniyalarga bir xil maʼlumot asosida ishonchli qaror qabul qilishda yordam beramiz.',
    ],
    stats: [['6', ' til', 'Koʻp tilli maslahat'], ['4', ' bosqich', 'Kelishdan oldin → yashash'], ['3', ' kurs', '48·80·200 soat'], ['1', ' platforma', 'CRM + LMS integratsiyasi']],
    valuesTitle: 'Asosiy qadriyatlar',
    values: [['Maʼlumot boʻshligʻini yopish', 'Viza, qabul va hayot haqidagi maʼlumotlarni tasdiqlangan manbalar asosida shaffof beramiz.'], ['Maʼlumotga asoslangan maslahat', 'Keyingi qadamni taxmin bilan emas, oʻqish maʼlumotlari bilan tavsiya qilamiz.'], ['Oxirigacha birga', 'Kelishdan oldingi taʼlimdan ish va yashab qolishgacha bitta jamoa.']],
  },

  news: {
    noticeTitle: 'Eʼlonlar · Qabul',
    share: 'Ulashish',
    copied: 'Havola nusxalandi',
    items: [
      { tag: 'Qabul', date: '2026.10', title: '2027-yil mart semestri til kursi (D-4) boʻyicha maslahat boshlandi', body: 'Universitet til markazlarining 2027-yil bahorgi semestriga qabul maslahati boshlandi. Hujjatlar uchun kelishdan 4–6 oy oldin murojaat qilish tavsiya etiladi.' },
      { tag: 'Kurs', date: '2026.10', title: '80 soatlik Basic kursi noyabrda LIVE boshlanadi', body: 'Til markazidagi birinchi semestrga tayyorlanayotganlar uchun 80 soatlik Basic kursi noyabrda ochiladi. Guruhlar bepul daraja testidan soʻng belgilanadi.' },
      { tag: 'Hamkorlar', date: '2026.09', title: 'Xorijiy agentliklar uchun onlayn taqdimot (Vyetnam · Oʻzbekiston · Moʻgʻuliston)', body: 'Hamkor portali, qoʻshma brend taʼlim va hisob-kitob qoidalari tanishtiriladi. Ariza topshirgandan soʻng jadval yuboriladi.' },
      { tag: 'Kasb', date: '2026.09', title: 'Bitiruvchi xalqaro talabalar uchun hamkor kompaniyalarda ishga joylashish dasturi', body: 'Mutaxassislik va koreys tili darajasiga koʻra amaliyot va ish bilan bogʻlaymiz, rezyume va intervyu murabbiyligi bilan.' },
    ],
    faqTitle: 'Koʻp beriladigan savollar',
    faqs: [
      ['48, 80 yoki 200 soatlik kursni qanday tanlayman?', 'Maslahatchi bepul daraja testi, kelish vaqti va maqsadingizga koʻra tavsiya qiladi. Avval “Menga mos kursni topish” orqali tekshirib koʻring.'],
      ['Tavsiya kodi qanday qoʻllaniladi?', 'Tavsiya havolasi orqali kirganingizda kod 30 kun saqlanadi va arizada CRMga yoziladi. Havola boʻlmasa, kodni arizaga qoʻlda kiriting.'],
      ['Agentliklar talabalar jarayonini koʻra oladimi?', 'Ha. Hamkor portalida har bir talabaning maslahat, hujjat, daraja testi, oʻqish va qabul bosqichlari real vaqtda koʻrinadi, hisobotlarni yuklab olish mumkin.'],
      ['Viza talablari qaysi qoidalarga asoslanadi?', 'Koreya Immigratsiya xizmati (HiKorea) ning soʻnggi qoidalariga. Ular tez-tez oʻzgargani uchun topshirishdan oldin maslahatchi qayta tekshiradi.'],
      ['Qaysi tillarda maslahat olish mumkin?', 'Koreys, ingliz, vyetnam, xitoy, oʻzbek va moʻgʻul tillarida.'],
    ],
  },

  consult: {
    eyebrow: 'FREE COUNSELING',
    title: 'Bepul maslahat · Hamkorlik arizasi',
    desc: 'Arizangiz darhol CRMga tushadi va siz tanlagan tilda gaplashadigan xodim 1 ish kuni ichida bogʻlanadi.',
    typeLabel: 'Ariza turi',
    types: { student: 'Talaba · Ota-ona', partner: 'Agentlik · Hamkor', university: 'Universitet · Muassasa', company: 'Kompaniya · Korxona' },
    name: 'Ism',
    org: 'Tashkilot · kompaniya nomi',
    country: 'Davlat',
    countries: ['Vyetnam', 'Oʻzbekiston', 'Moʻgʻuliston', 'Xitoy', 'Nepal', 'Indoneziya', 'Koreya', 'Boshqa'],
    phone: 'Telefon · messenjer ID',
    email: 'Email',
    contactPref: 'Qulay aloqa usuli',
    contactPrefs: ['Telefon', 'Telegram', 'WhatsApp', 'KakaoTalk', 'Zalo', 'Email'],
    interest: 'Qiziqish sohasi',
    interests: { student: ['Kelishdan oldin koreys tili 48 soat', 'Kelishdan oldin koreys tili 80 soat', 'Kelishdan oldin koreys tili 200 soat', 'D-4 Til kursi', 'D-2 Bakalavr · Magistratura', 'Ish · Startap · Yashash'], partner: ['Hamkorlik shartnomasi', 'Kelishdan oldingi taʼlimni topshirish', 'Talabalarni roʻyxat · boshqaruv', 'Mahalliy koʻrgazmalar'], university: ['Talaba tavsiyasi', 'Qabulgacha taʼlim', 'Qabul taqdimotlari'], company: ['Xalqaro talabalarni ishga olish', 'Amaliyot', 'Xodimlar uchun koreys tili'] },
    message: 'Xabar',
    messagePh: 'Koreys tili darajangiz, kelish vaqti va savollaringizni yozing.',
    refCode: 'Tavsiya · xodim · hamkor kodi (ixtiyoriy)',
    refApplied: 'Tavsiya kodi qoʻllanildi',
    consent: 'Maslahat uchun shaxsiy maʼlumotlarim (ism, aloqa, davlat) toʻplanishi va ishlatilishiga roziman. Ular qonunga muvofiq saqlanadi va yoʻq qilinadi.',
    submit: 'Maslahatga yozilish',
    sending: 'Yuborilmoqda…',
    success: 'Arizangiz qabul qilindi. Tez orada siz bilan bogʻlanamiz.',
    demoNote: 'Demo rejim: haqiqiy CRMga yuborish uchun CRM endpoint (VITE_CRM_ENDPOINT) ni sozlang.',
    error: 'Xatolik yuz berdi. Keyinroq urinib koʻring yoki email orqali yozing.',
    required: 'Majburiy maydonlarni toʻldiring.',
    again: 'Yangi ariza',
    sideTitle: 'Bevosita bogʻlanish',
    sideEmail: 'Email yozish',
    sideKakao: 'KakaoTalk kanali',
    sideLevel: 'Bepul daraja testi',
    sideHours: 'Ish vaqti: Du–Ju 09:00–18:00 (Koreya vaqti)',
  },

  footer: {
    desc: 'Kelishdan oldingi koreys tilidan til kursi, bakalavr · magistratura, ish va yashab qolishgacha — CRM va LMS bilan bogʻlangan xalqaro talabalar platformasi.',
    rights: 'All rights reserved.',
  },
}

export default uz
