const vi = {
  meta: { title: 'Global C&B | Tương lai và ước mơ của bạn bắt đầu từ đây' },

  ui: {
    audiences: ['Học sinh · Phụ huynh', 'Trung tâm du học · Đối tác nước ngoài', 'Trường đại học · Cơ sở giáo dục', 'Doanh nghiệp'],
    search: 'Tìm kiếm',
    searchPlaceholder: 'Bạn muốn tìm gì? (VD: học tiếng, giới thiệu, trung tâm du học)',
    noResult: 'Không có kết quả. Hãy đăng ký tư vấn để được hướng dẫn trực tiếp.',
    menu: 'Menu',
    close: 'Đóng',
    home: 'Trang chủ',
    nav: ['Tư vấn · Đối tác', 'Giới thiệu', 'Tiếng Hàn · Trước nhập cảnh', 'D-4 Học tiếng', 'D-2 Đại học · Cao học', 'Việc làm · Khởi nghiệp · Định cư', 'Tin tức · Chia sẻ'],
    more: 'Xem thêm',
    consultNow: 'Tư vấn miễn phí',
    next: 'Bước tiếp theo',
    prev: 'Bước trước',
    language: 'Ngôn ngữ',
  },

  menu: [
    { route: 'consult', links: [['form', 'Đăng ký tư vấn 1:1'], ['portals', 'Đăng nhập nền tảng'], ['referral', 'Chương trình giới thiệu bạn bè'], ['share-link', 'Tạo link giới thiệu / quảng bá'], ['sales', 'Hỗ trợ nhân viên quảng bá · kinh doanh'], ['partners', 'Đối tác trung tâm du học B2B'], ['institutions', 'Hợp tác trường · doanh nghiệp']] },
    { route: 'about', links: [['mission', 'Giới thiệu Global C&B'], ['platform', 'Nền tảng CRM · LMS'], ['values', 'Giá trị cốt lõi']] },
    { route: 'pre-departure', links: [['courses', 'Khóa 48·80·200 giờ'], ['compare', 'Bảng so sánh khóa học'], ['course-finder', 'Tìm khóa học phù hợp']] },
    { route: 'd4', links: [['overview', 'Tổng quan học tiếng'], ['steps', 'Quy trình'], ['support', 'Nội dung hỗ trợ']] },
    { route: 'd2', links: [['overview', 'Tổng quan đại học · cao học'], ['steps', 'Quy trình'], ['support', 'Nội dung hỗ trợ']] },
    { route: 'career', links: [['overview', 'Tổng quan việc làm · định cư'], ['steps', 'Quy trình'], ['support', 'Nội dung hỗ trợ']] },
    { route: 'news', links: [['notice', 'Thông báo · Tuyển sinh'], ['faq', 'Câu hỏi thường gặp']] },
  ],

  hero: {
    badge: 'GLOBAL C&B',
    title1: 'Tương lai và ước mơ của bạn,',
    title2: 'bắt đầu từ đây.',
    desc: 'Tiếng Hàn trước nhập cảnh, khóa học tiếng và tuyển sinh đại học. Cùng chuẩn bị bước tiếp theo phù hợp với trình độ và mục tiêu của bạn.',
    ctaConsult: 'Tư vấn khóa học phù hợp',
    ctaCompare: 'So sánh 48·80·200 giờ',
    chips: ['Đào tạo trước nhập cảnh theo trình độ', 'Tư vấn đại học · nghề nghiệp'],
    cardTitle: 'Người đồng hành thiết kế tương lai',
    cardSub: 'Giáo dục · Học lên · Tư vấn nghề nghiệp',
  },

  home: {
    audienceTitle: 'Global C&B dành cho ai?',
    audienceDesc: 'Học sinh, trung tâm du học, trường đại học và doanh nghiệp đều sử dụng dịch vụ mình cần trên một nền tảng.',
    audiences: [
      { title: 'Học sinh · Phụ huynh', desc: 'Lộ trình 1:1 từ học trước nhập cảnh đến đại học và việc làm', route: 'pre-departure' },
      { title: 'Trung tâm du học · Đối tác', desc: 'Đăng ký, theo dõi học sinh và đối soát hoa hồng minh bạch', route: 'consult/partners' },
      { title: 'Trường đại học · Cơ sở giáo dục', desc: 'Ứng viên có lịch sử học tập được xác minh, ủy thác đào tạo', route: 'consult/institutions' },
      { title: 'Doanh nghiệp', desc: 'Kết nối du học sinh có tiếng Hàn và chuyên ngành được xác minh', route: 'consult/institutions' },
    ],
    pathTitle: 'Từ trước nhập cảnh đến định cư: hành trình 4 bước',
    pathDesc: 'Đào tạo và tư vấn ở mỗi giai đoạn được kết nối liền mạch qua CRM và LMS.',
    path: [
      { step: '01', title: 'Tiếng Hàn · Trước nhập cảnh', desc: 'Khóa 48·80·200 giờ theo trình độ và chuẩn bị nhập cảnh', route: 'pre-departure' },
      { step: '02', title: 'D-4 Học tiếng', desc: 'Nhập học viện ngôn ngữ, visa, ổn định cuộc sống, chuyên cần', route: 'd4' },
      { step: '03', title: 'D-2 Đại học · Cao học', desc: 'Gợi ý trường dựa trên dữ liệu và hỗ trợ nhập học', route: 'd2' },
      { step: '04', title: 'Việc làm · Khởi nghiệp · Định cư', desc: 'Thực tập, tuyển dụng, khởi nghiệp và định cư lâu dài', route: 'career' },
    ],
    growTitle: 'Cùng lan tỏa, cùng phát triển',
    growDesc: 'Đóng góp của học sinh giới thiệu, nhân viên quảng bá và trung tâm du học đều được ghi nhận chính xác trên nền tảng.',
    grow: [
      { title: 'Giới thiệu bạn bè', desc: 'Giới thiệu bạn bè, cả hai cùng nhận ưu đãi', route: 'consult/referral' },
      { title: 'Nhân viên quảng bá · kinh doanh', desc: 'Link cá nhân, bộ tài liệu, bảng hiệu suất', route: 'consult/sales' },
      { title: 'Trung tâm du học B2B', desc: 'Cổng đối tác, đào tạo đồng thương hiệu, đối soát', route: 'consult/partners' },
    ],
    ctaTitle: 'Hãy xác định bước tiếp theo phù hợp với bạn ngay hôm nay',
    ctaDesc: 'Nhận lộ trình khóa học, học lên và nghề nghiệp với bài kiểm tra trình độ miễn phí và tư vấn 1:1.',
  },

  pages: {
    consult: { eyebrow: 'MY COUNSELING · PARTNERS', title: 'Tư vấn · Đối tác', desc: 'Bắt đầu tại đây: đăng ký tư vấn, link giới thiệu và quảng bá, đăng ký đối tác trung tâm du học, trường học và doanh nghiệp.' },
    about: { eyebrow: 'ABOUT GLOBAL C&B', title: 'Giới thiệu', desc: 'Global C&B là nền tảng hành trình du học kết nối Giáo dục (Campus) và Nghề nghiệp (Career).' },
    'pre-departure': { eyebrow: 'KOREAN · PRE-DEPARTURE', title: 'Tiếng Hàn · Trước nhập cảnh', desc: 'Học tiếng Hàn theo trình độ trước khi nhập cảnh để tự tin với học kỳ đầu tiên và rút ngắn thời gian vào đại học.' },
    news: { eyebrow: 'NEWS · SHARE', title: 'Tin tức · Chia sẻ', desc: 'Xem lịch tuyển sinh, khai giảng và hội thảo đối tác, rồi chia sẻ với bạn bè.' },
  },

  courses: {
    eyebrow: 'PRE-DEPARTURE COURSES',
    title: 'Đào tạo trước nhập cảnh theo trình độ: 48 · 80 · 200 giờ',
    desc: 'Mọi khóa học đều ghi nhận kiểm tra trình độ, chuyên cần và kết quả trên LMS; báo cáo học tập được chia sẻ với tư vấn viên.',
    hoursUnit: 'giờ',
    recommended: 'Đề xuất',
    targetLabel: 'Đối tượng',
    goalLabel: 'Mục tiêu học tập',
    outcomeLabel: 'Kết quả',
    items: [
      {
        hours: 48, name: 'Starter', tagline: 'Từ bảng chữ Hangul đến tiếng Hàn đời sống', period: 'Khoảng 4–6 tuần · LIVE trực tuyến + VOD',
        target: 'Người mới bắt đầu hoặc chỉ đọc được Hangul',
        goal: 'Đọc viết Hangul, giới thiệu bản thân, mẫu câu thiết yếu khi nhập cảnh và sinh hoạt',
        modules: ['Chữ cái và phát âm Hangul', 'Tiếng Hàn sinh tồn (sân bay, nhà ở, ngân hàng)', 'Luật cơ bản và phép lịch sự', 'Định hướng trước nhập cảnh'],
        outcome: 'Sẵn sàng cho cấp 1 viện ngôn ngữ',
      },
      {
        hours: 80, name: 'Basic', tagline: 'Tự tin bước vào học kỳ đầu tiên', period: 'Khoảng 8–10 tuần · Lớp LIVE + nhận xét bài tập',
        target: 'Học sinh chuẩn bị nhập học khóa tiếng (D-4)',
        goal: 'Từ vựng, ngữ pháp TOPIK I cấp 1, làm quen nghe giảng bằng tiếng Hàn',
        modules: ['800 từ vựng và ngữ pháp cơ bản', 'Tập trung nghe · nói', 'Làm quen dạng đề TOPIK I', 'Văn hóa Hàn Quốc · đời sống campus'],
        outcome: 'Mục tiêu TOPIK I cấp 1 · xếp lớp cao hơn',
        highlight: true,
      },
      {
        hours: 200, name: 'Intensive', tagline: 'Rút ngắn thời gian học tiếng và vào đại học', period: 'Khoảng 16–20 tuần · LIVE nhóm nhỏ + kèm 1:1',
        target: 'Học sinh muốn vào đại học (D-2) sớm hoặc giành học bổng',
        goal: 'TOPIK I cấp 2 trở lên, tiếng Hàn học thuật cơ bản',
        modules: ['Hoàn thiện ngữ pháp sơ cấp', 'Thi thử TOPIK I', 'Tiếng Hàn học thuật · thuyết trình', 'Tư vấn học lên · chuẩn bị hồ sơ'],
        outcome: 'Mục tiêu TOPIK I cấp 2 · tư vấn học lên',
      },
    ],
    compareTitle: 'Bảng so sánh khóa học',
    compareHead: 'Hạng mục',
    compareRows: [
      ['Tổng số giờ học', '48 giờ', '80 giờ', '200 giờ'],
      ['Kiểm tra trình độ (đầu · cuối khóa)', '○', '○', '○'],
      ['Lớp LIVE', '2 buổi/tuần', '3 buổi/tuần', '4–5 buổi/tuần'],
      ['Nhận xét bài tập · phát âm', '-', '○', '○ (1:1)'],
      ['Thi thử TOPIK', '-', '1 lần', '3 lần'],
      ['Báo cáo học tập → tư vấn viên', '○', '○', '○'],
      ['Tư vấn đại học · nghề nghiệp', 'Cơ bản', 'Cơ bản', 'Chuyên sâu'],
    ],
    finder: {
      title: 'Tìm khóa học phù hợp',
      desc: 'Trả lời 3 câu hỏi để nhận gợi ý khóa học. Kết quả sẽ tự động được điền vào phiếu tư vấn.',
      questions: [
        { q: 'Trình độ tiếng Hàn hiện tại của bạn?', options: ['Mới bắt đầu / chỉ biết Hangul', 'Chào hỏi · giới thiệu đơn giản', 'Khoảng TOPIK cấp 1'] },
        { q: 'Mục tiêu đầu tiên của bạn tại Hàn Quốc?', options: ['Học tiếng từng bước tại viện ngôn ngữ', 'Học tiếng rồi vào đại học', 'Vào đại học · cao học sớm nhất có thể'] },
        { q: 'Còn bao lâu nữa bạn nhập cảnh?', options: ['Dưới 2 tháng', '2–4 tháng', 'Trên 4 tháng'] },
      ],
      resultLabel: 'Khóa học đề xuất',
      resultDesc: 'Tư vấn viên sẽ xác nhận xếp lớp sau bài kiểm tra trình độ miễn phí.',
      cta: 'Đăng ký tư vấn khóa này',
      levelTest: 'Làm bài kiểm tra miễn phí',
      restart: 'Làm lại',
    },
  },

  stages: {
    factsLabel: 'Thông tin chính',
    stepsLabel: 'Quy trình',
    supportLabel: 'Global C&B hỗ trợ bạn',
    disclaimer: 'Điều kiện visa có thể thay đổi theo quy định mới nhất của Cục Xuất nhập cảnh Hàn Quốc (HiKorea). Chúng tôi sẽ kiểm tra lại quy định hiện hành khi tư vấn.',
    items: {
      d4: {
        eyebrow: 'STEP 02 · D-4',
        title: 'D-4 Học tiếng',
        summary: 'Giai đoạn học chương trình tiếng Hàn chính quy tại viện ngôn ngữ trực thuộc đại học. Chúng tôi đồng hành từ hồ sơ nhập học, chứng minh tài chính, xin visa đến ổn định cuộc sống, chuyên cần và điểm số.',
        steps: [
          ['Kiểm tra trình độ · tư vấn', 'Gợi ý viện ngôn ngữ và kỳ học phù hợp trình độ, mục tiêu'],
          ['Nộp hồ sơ', 'Đơn nhập học, học bạ và giấy tờ chứng minh tài chính'],
          ['Visa · nhập cảnh', 'Xin visa D-4 sau khi có giấy báo nhập học, định hướng nhập cảnh'],
          ['Ổn định · học tập', 'Đăng ký người nước ngoài, ngân hàng, nhà ở; quản lý chuyên cần và điểm'],
        ],
        support: ['Kết nối viện ngôn ngữ đại học · hướng dẫn hồ sơ', 'Danh sách kiểm tra chứng minh tài chính và visa D-4', 'Hướng dẫn đón sân bay, nhà ở, đăng ký cư trú, ngân hàng, SIM', 'Quản lý chuyên cần · điểm trên LMS để phòng rủi ro visa', 'Hướng dẫn điều kiện xin phép làm thêm'],
        facts: [['Kỳ học', 'Thường 4 kỳ/năm, mỗi kỳ khoảng 10 tuần'], ['Mục tiêu vào đại học', 'TOPIK cấp 3 trở lên (tùy trường, ngành)'], ['Khóa nên học trước', 'Khóa 80 hoặc 200 giờ trước nhập cảnh']],
      },
      d2: {
        eyebrow: 'STEP 03 · D-2',
        title: 'D-2 Đại học · Cao học',
        summary: 'Dựa trên dữ liệu học tập LMS và điểm TOPIK, chúng tôi gợi ý trường, ngành có thể ứng tuyển và hỗ trợ hồ sơ nhập học đến chuyển đổi sang visa D-2.',
        steps: [
          ['Đánh giá học lên', 'Báo cáo gợi ý trường/ngành theo TOPIK, điểm và nguyện vọng'],
          ['Chuẩn bị hồ sơ', 'Sửa bài giới thiệu bản thân, kế hoạch học tập, luyện phỏng vấn'],
          ['Trúng tuyển · visa', 'Xin visa D-2 hoặc chuyển từ D-4 sang D-2 sau khi trúng tuyển'],
          ['Quản lý học tập', 'Kèm cặp tín chỉ và điều kiện tốt nghiệp từng học kỳ'],
        ],
        support: ['Báo cáo gợi ý trường/ngành theo điểm và nguyện vọng', 'Sửa bài luận, kế hoạch học tập, chuẩn bị phỏng vấn', 'Thông tin học bổng, ký túc xá, trường đạt chứng nhận IEQAS', 'Hướng dẫn hồ sơ chuyển visa D-4 → D-2', 'Kèm cặp tín chỉ và điều kiện tốt nghiệp (VD: TOPIK 4)'],
        facts: [['Chương trình', 'Đại học (D-2-2) · Thạc sĩ (D-2-3) · Tiến sĩ (D-2-4)'], ['Yêu cầu tiếng', 'Thường TOPIK 3 trở lên; nhiều trường yêu cầu cấp 4 khi tốt nghiệp'], ['Kỳ tuyển sinh', 'Kỳ tháng 3 · tháng 9 (tùy trường)']],
      },
      career: {
        eyebrow: 'STEP 04 · CAREER',
        title: 'Việc làm · Khởi nghiệp · Định cư',
        summary: 'Thiết kế con đường sau tốt nghiệp: tìm việc, làm việc tại doanh nghiệp Hàn Quốc, khởi nghiệp và định cư tại địa phương — kết nối với nguồn nhân lực của doanh nghiệp đối tác.',
        steps: [
          ['Định hướng nghề nghiệp', 'Tư vấn theo chuyên ngành, ngôn ngữ và khu vực mong muốn'],
          ['Chuẩn bị năng lực', 'Kèm CV, thư xin việc, phỏng vấn; tiếng Hàn công sở'],
          ['Kết nối · tuyển dụng', 'Thực tập, tuyển dụng tại doanh nghiệp đối tác, hướng dẫn visa'],
          ['Định cư · khởi nghiệp', 'Chương trình định cư dài hạn, đào tạo khởi nghiệp và mạng lưới'],
        ],
        support: ['Lộ trình visa tìm việc (D-10), chuyên môn (E-7), địa phương (F-2-R)', 'Kết nối thực tập · tuyển dụng, kèm CV và phỏng vấn', 'Chương trình khởi nghiệp công nghệ (D-8-4) và đào tạo khởi nghiệp', 'Chuẩn bị định cư lâu dài như chương trình hội nhập KIIP', 'Mạng lưới khởi nghiệp · việc làm sau khi về nước'],
        facts: [['Kết nối', 'Nguồn nhân lực doanh nghiệp đối tác · chương trình định cư địa phương'], ['Đào tạo', 'Tiếng Hàn công sở · văn hóa doanh nghiệp'], ['Quy định', 'Theo thông báo mới nhất của HiKorea']],
      },
    },
  },

  platform: {
    eyebrow: 'CRM × LMS PLATFORM',
    title: 'Tư vấn (CRM) và học tập (LMS) vận hành như một',
    desc: 'Ai đã giới thiệu bạn và bạn đã học được gì đều nằm trong một hồ sơ học sinh — căn cứ để gợi ý bước tiếp theo.',
    flow: [
      ['INFLOW', 'Giới thiệu · nhân viên · trung tâm · SNS', 'Mọi yêu cầu từ link có mã giới thiệu hoặc UTM đều được ghi nhận cùng nguồn.'],
      ['CRM', 'Ghi nhận · tự động phân công', 'Phân công tư vấn viên theo quốc gia, ngôn ngữ, khóa học; lưu lịch sử tư vấn.'],
      ['LMS', 'Kiểm tra trình độ · học', 'Gợi ý khóa học từ kết quả kiểm tra, ghi nhận chuyên cần và kết quả.'],
      ['SYNC', 'Dữ liệu học → tư vấn', 'Báo cáo học tập quay về CRM làm căn cứ tư vấn học lên, học bổng, visa.'],
      ['MATCH', 'Trường · doanh nghiệp', 'Giới thiệu học sinh có lịch sử học tập được xác minh đến trường và doanh nghiệp.'],
    ],
    crmTitle: 'CRM · Quản lý tư vấn',
    crmFeatures: ['Quản lý khách hàng theo nguồn (người giới thiệu · nhân viên · trung tâm · chiến dịch)', 'Tự động phân công theo quốc gia, ngôn ngữ; dòng thời gian tư vấn', 'Quy trình hồ sơ · visa · nhập học và nhắc hạn', 'Dữ liệu tính thưởng giới thiệu và hoa hồng đối tác', 'Thông báo qua KakaoTalk, Zalo, WhatsApp, email'],
    lmsTitle: 'LMS · Quản lý học tập',
    lmsFeatures: ['Kiểm tra trình độ trực tuyến và gợi ý khóa học tự động', 'Học LIVE · VOD 48·80·200 giờ, quản lý chuyên cần · bài tập', 'Chia sẻ báo cáo học tập với học sinh, phụ huynh, trung tâm, tư vấn viên', 'Thi thử TOPIK và bảng thành tích', 'Định hướng luật cơ bản, phép lịch sự, đời sống campus'],
  },

  portals: {
    eyebrow: 'PLATFORM LOGIN',
    title: 'Truy cập nền tảng theo vai trò',
    desc: 'Cùng một dữ liệu học sinh, hiển thị theo vai trò của bạn.',
    items: [
      { key: 'lms', title: 'LMS Học sinh · Phụ huynh', desc: 'Kiểm tra trình độ, khóa học, báo cáo, link giới thiệu của tôi', cta: 'Đăng nhập LMS' },
      { key: 'partner', title: 'Cổng đối tác trung tâm du học', desc: 'Đăng ký · tiến độ học sinh, báo cáo, đối soát hoa hồng', cta: 'Đăng nhập đối tác' },
      { key: 'staff', title: 'CRM nhân viên', desc: 'Phân công khách hàng, lịch sử tư vấn, hiệu suất quảng bá', cta: 'Đăng nhập nhân viên' },
      { key: 'institution', title: 'Cổng trường · doanh nghiệp', desc: 'Hồ sơ học sinh được giới thiệu, đào tạo ủy thác, tuyển dụng', cta: 'Đăng nhập tổ chức' },
    ],
  },

  referral: {
    eyebrow: 'STUDENT REFERRAL',
    title: 'Bắt đầu cùng bạn bè, nhận ưu đãi cùng nhau',
    desc: 'Học viên, cựu học viên và phụ huynh đều có thể giới thiệu. Lượt giới thiệu được ghi tự động vào CRM nên không bỏ sót phần thưởng.',
    steps: [
      ['Nhận link giới thiệu', 'Nhận link cá nhân trên trang LMS hoặc công cụ tạo link bên dưới.'],
      ['Chia sẻ với bạn bè', 'Chia sẻ qua KakaoTalk, Zalo, Facebook, Telegram — thông tin giới thiệu được giữ 30 ngày.'],
      ['Theo dõi tiến độ', 'Xem tình trạng tư vấn · đăng ký của bạn bè trên trang cá nhân.'],
      ['Cùng nhận ưu đãi', 'Khi đăng ký thành công, cả hai cùng nhận giảm học phí, giáo trình hoặc điểm thưởng.'],
    ],
    note: 'Ưu đãi và điều kiện áp dụng theo thông báo khuyến mãi từng mùa.',
  },

  sales: {
    eyebrow: 'STAFF SALES KIT',
    title: 'Nhân viên quảng bá · kinh doanh, kết quả rõ ràng',
    desc: 'Dù quảng bá tại hội chợ, hội thảo hay mạng xã hội, mã cá nhân giúp theo dõi từ lượt truy cập đến đăng ký.',
    tools: [
      ['Link · QR cá nhân', 'Mọi yêu cầu từ link có mã nhân viên được tính vào thành tích cá nhân.'],
      ['Bộ tài liệu đa ngôn ngữ', 'Card news, brochure, video bằng 6 ngôn ngữ, luôn là bản mới nhất.'],
      ['Quy trình khách hàng', 'Xem học sinh của bạn: tư vấn → kiểm tra → đăng ký → nhập cảnh.'],
      ['Bảng hiệu suất', 'Tỷ lệ chuyển đổi theo kênh, tiến độ mục tiêu và căn cứ thưởng theo thời gian thực.'],
    ],
  },

  linkGen: {
    title: 'Tạo link giới thiệu · quảng bá',
    desc: 'Nhập mã để tạo ngay link theo dõi và mã QR. Yêu cầu tư vấn từ link này được ghi vào CRM cùng nguồn.',
    roleLabel: 'Tôi là',
    roles: { ref: 'Học sinh · phụ huynh giới thiệu', staff: 'Nhân viên Global C&B', partner: 'Trung tâm du học · đối tác' },
    codeLabel: 'Mã của tôi',
    codePh: 'VD: MINH2026, ST-KIM01, VN-HANOI',
    channelLabel: 'Kênh chia sẻ',
    channels: { kakao: 'KakaoTalk', zalo: 'Zalo', facebook: 'Facebook', telegram: 'Telegram', instagram: 'Instagram', offline: 'Offline · QR' },
    campaignLabel: 'Tên chiến dịch (tùy chọn)',
    campaignPh: 'VD: 2027-spring-fair',
    result: 'Link của tôi',
    copy: 'Sao chép',
    copied: 'Đã sao chép',
    share: 'Chia sẻ',
    downloadQr: 'Lưu QR',
    empty: 'Nhập mã để tạo link.',
    shareText: 'Cùng chuẩn bị du học Hàn Quốc với Global C&B nhé!',
  },

  partners: {
    eyebrow: 'B2B AGENCY PARTNERS',
    title: 'Cùng trung tâm du học và đối tác phát triển thị trường du học',
    desc: 'Đối tác tuyển sinh, Global C&B quản lý đào tạo, nhập học và ổn định cuộc sống. Mọi tiến độ và dữ liệu đối soát đều được chia sẻ minh bạch trên nền tảng.',
    benefits: [
      ['Cổng đối tác riêng', 'Đăng ký học sinh hàng loạt, theo dõi hồ sơ · visa · nhập học theo thời gian thực.'],
      ['Ủy thác đào tạo trước nhập cảnh', 'Vận hành khóa 48·80·200 giờ đồng thương hiệu và nhận báo cáo học tập.'],
      ['Đối soát hoa hồng minh bạch', 'Học sinh từ mã đối tác được tổng hợp tự động trong CRM và đối soát hàng tháng.'],
      ['Chia sẻ mạng lưới đại học', 'Ưu tiên cung cấp thông tin tuyển sinh, học bổng và lịch nhập học của trường đối tác.'],
      ['Đào tạo tư vấn viên', 'Webinar định kỳ về thay đổi quy định visa, tuyển sinh và kinh nghiệm tư vấn.'],
      ['Đồng tổ chức hội thảo', 'Cùng tổ chức hội thảo du học tại Việt Nam, Uzbekistan, Mông Cổ, Trung Quốc...'],
    ],
    stepsTitle: 'Quy trình trở thành đối tác',
    steps: ['Đăng ký đối tác', 'Ký hợp tác · cấp mã', 'Hướng dẫn cổng · đào tạo', 'Đăng ký · quản lý học sinh', 'Đối soát hàng tháng'],
    cta: 'Đăng ký đối tác',
  },

  institutions: {
    eyebrow: 'UNIVERSITY · COMPANY',
    title: 'Hợp tác với trường đại học · doanh nghiệp',
    desc: 'Kết nối du học sinh được xác minh bằng dữ liệu học tập với trường đại học và doanh nghiệp.',
    items: [
      { title: 'Trường đại học · Cơ sở giáo dục', desc: 'Nhận học sinh có lịch sử học tập và trình độ được xác minh trên LMS, ủy thác đào tạo tiếng Hàn và định hướng trước nhập học.', points: ['Nguồn ứng viên được xác minh (chuyên cần · kết quả · TOPIK)', 'Ủy thác tiếng Hàn · định hướng trước nhập học', 'Báo cáo phòng ngừa bỏ học', 'Đồng tổ chức hội thảo tuyển sinh nước ngoài'], cta: 'Hợp tác với trường' },
      { title: 'Doanh nghiệp', desc: 'Kết nối nhân tài du học sinh có tiếng Hàn và chuyên ngành được xác minh qua thực tập, tuyển dụng; đào tạo tiếng Hàn cho nhân viên.', points: ['Nguồn nhân lực theo chuyên ngành · ngôn ngữ', 'Hỗ trợ thực tập · tuyển dụng và hướng dẫn visa', 'Đào tạo tiếng Hàn · nghiệp vụ cho nhân viên nước ngoài', 'Giới thiệu nhân sự địa phương khi mở rộng ra nước ngoài'], cta: 'Hợp tác doanh nghiệp' },
    ],
  },

  about: {
    missionTitle: 'Từ Giáo dục (Campus) đến Nghề nghiệp (Career), kết nối hành trình của mỗi người',
    mission: [
      'Học sinh và gia đình chuẩn bị du học Hàn Quốc phải đưa ra quyết định giữa nhiều thông tin khác nhau theo quốc gia, trường và loại visa. Để thu hẹp khoảng cách thông tin, Global C&B thiết kế đào tạo trước nhập cảnh, học tiếng, học đại học · cao học, việc làm và định cư thành một hành trình.',
      'Bằng cách kết nối hồ sơ tư vấn (CRM) và hồ sơ học tập (LMS) thành một hồ sơ học sinh, chúng tôi giúp học sinh, phụ huynh, trung tâm du học, trường đại học và doanh nghiệp ra quyết định đáng tin cậy từ cùng một dữ liệu.',
    ],
    stats: [['6', ' ngôn ngữ', 'Tư vấn đa ngôn ngữ'], ['4', ' bước', 'Trước nhập cảnh → định cư'], ['3', ' khóa', '48·80·200 giờ'], ['1', ' nền tảng', 'Tích hợp CRM + LMS']],
    valuesTitle: 'Giá trị cốt lõi',
    values: [['Thu hẹp khoảng cách thông tin', 'Hướng dẫn minh bạch về visa, nhập học và đời sống theo nguồn đã xác minh.'], ['Tư vấn dựa trên dữ liệu', 'Gợi ý bước tiếp theo bằng dữ liệu học tập, không phải cảm tính.'], ['Đồng hành đến cùng', 'Một đội ngũ từ đào tạo trước nhập cảnh đến việc làm và định cư.']],
  },

  news: {
    noticeTitle: 'Thông báo · Tuyển sinh',
    share: 'Chia sẻ',
    copied: 'Đã sao chép link',
    items: [
      { tag: 'Tuyển sinh', date: '2026.10', title: 'Mở tư vấn nhập học khóa tiếng (D-4) kỳ tháng 3/2027', body: 'Bắt đầu tư vấn nhập học viện ngôn ngữ kỳ xuân 2027. Nên tư vấn trước 4–6 tháng để kịp chuẩn bị hồ sơ.' },
      { tag: 'Đào tạo', date: '2026.10', title: 'Khai giảng LIVE khóa Basic 80 giờ tháng 11', body: 'Khóa Basic 80 giờ dành cho học sinh chuẩn bị học kỳ đầu tại viện ngôn ngữ khai giảng tháng 11. Xếp lớp sau bài kiểm tra miễn phí.' },
      { tag: 'Đối tác', date: '2026.09', title: 'Hội thảo trực tuyến cho trung tâm du học (Việt Nam · Uzbekistan · Mông Cổ)', body: 'Giới thiệu cách dùng cổng đối tác, ủy thác đào tạo đồng thương hiệu và quy định đối soát. Lịch sẽ được gửi sau khi đăng ký.' },
      { tag: 'Nghề nghiệp', date: '2026.09', title: 'Chương trình kết nối tuyển dụng cho du học sinh sắp tốt nghiệp', body: 'Kết nối thực tập và tuyển dụng tại doanh nghiệp đối tác theo chuyên ngành và trình độ tiếng Hàn, kèm hỗ trợ CV và phỏng vấn.' },
    ],
    faqTitle: 'Câu hỏi thường gặp',
    faqs: [
      ['Chọn khóa 48, 80 hay 200 giờ như thế nào?', 'Tư vấn viên sẽ đề xuất dựa trên bài kiểm tra trình độ miễn phí, thời điểm nhập cảnh và mục tiêu. Bạn có thể thử trước với “Tìm khóa học phù hợp”.'],
      ['Mã giới thiệu được áp dụng thế nào?', 'Khi truy cập bằng link giới thiệu, mã được lưu 30 ngày và ghi vào CRM khi đăng ký tư vấn. Nếu không có link, hãy nhập mã vào phiếu đăng ký.'],
      ['Trung tâm du học có xem được tiến độ học sinh không?', 'Có. Cổng đối tác hiển thị tư vấn, hồ sơ, kiểm tra trình độ, học tập và nhập học của từng học sinh theo thời gian thực, kèm báo cáo tải về.'],
      ['Điều kiện visa theo quy định nào?', 'Theo quy định mới nhất của Cục Xuất nhập cảnh Hàn Quốc (HiKorea). Vì quy định thay đổi thường xuyên, tư vấn viên sẽ kiểm tra lại trước khi nộp.'],
      ['Có thể tư vấn bằng ngôn ngữ nào?', 'Tiếng Hàn, tiếng Anh, tiếng Việt, tiếng Trung, tiếng Uzbek và tiếng Mông Cổ.'],
    ],
  },

  consult: {
    eyebrow: 'FREE COUNSELING',
    title: 'Tư vấn miễn phí · Đăng ký đối tác',
    desc: 'Thông tin được ghi ngay vào CRM và tư vấn viên nói ngôn ngữ bạn chọn sẽ liên hệ trong 1 ngày làm việc.',
    typeLabel: 'Loại đăng ký',
    types: { student: 'Học sinh · Phụ huynh', partner: 'Trung tâm · Đối tác', university: 'Trường · Cơ sở giáo dục', company: 'Doanh nghiệp' },
    name: 'Họ tên',
    org: 'Tên tổ chức · công ty',
    country: 'Quốc gia',
    countries: ['Việt Nam', 'Uzbekistan', 'Mông Cổ', 'Trung Quốc', 'Nepal', 'Indonesia', 'Hàn Quốc', 'Khác'],
    phone: 'Số điện thoại · ID nhắn tin',
    email: 'Email',
    contactPref: 'Cách liên hệ ưu tiên',
    contactPrefs: ['Điện thoại', 'KakaoTalk', 'Zalo', 'WhatsApp', 'Telegram', 'Email'],
    interest: 'Lĩnh vực quan tâm',
    interests: { student: ['Tiếng Hàn trước nhập cảnh 48 giờ', 'Tiếng Hàn trước nhập cảnh 80 giờ', 'Tiếng Hàn trước nhập cảnh 200 giờ', 'D-4 Học tiếng', 'D-2 Đại học · Cao học', 'Việc làm · Khởi nghiệp · Định cư'], partner: ['Hợp đồng đối tác', 'Ủy thác đào tạo trước nhập cảnh', 'Đăng ký · quản lý học sinh', 'Hội thảo tại địa phương'], university: ['Giới thiệu học sinh', 'Ủy thác đào tạo trước nhập học', 'Hội thảo tuyển sinh'], company: ['Tuyển dụng du học sinh', 'Thực tập', 'Đào tạo tiếng Hàn cho nhân viên'] },
    message: 'Nội dung',
    messagePh: 'Hãy ghi trình độ tiếng Hàn, thời gian dự kiến nhập cảnh và câu hỏi của bạn.',
    refCode: 'Mã giới thiệu · nhân viên · đối tác (tùy chọn)',
    refApplied: 'Đã áp dụng mã giới thiệu',
    consent: 'Tôi đồng ý cho thu thập và sử dụng thông tin cá nhân (họ tên, liên hệ, quốc gia) để tư vấn. Thông tin được lưu và hủy theo quy định pháp luật.',
    submit: 'Đăng ký tư vấn',
    sending: 'Đang gửi…',
    success: 'Đã nhận đăng ký. Tư vấn viên sẽ sớm liên hệ với bạn.',
    demoNote: 'Chế độ demo: hãy cấu hình CRM endpoint (VITE_CRM_ENDPOINT) để gửi đến CRM thật.',
    error: 'Đã xảy ra lỗi. Vui lòng thử lại sau hoặc liên hệ qua email.',
    required: 'Vui lòng điền các mục bắt buộc.',
    again: 'Đăng ký mới',
    sideTitle: 'Liên hệ trực tiếp',
    sideEmail: 'Gửi email',
    sideKakao: 'Kênh KakaoTalk',
    sideLevel: 'Kiểm tra trình độ miễn phí',
    sideHours: 'Giờ tư vấn: Thứ 2–6, 09:00–18:00 (giờ Hàn Quốc)',
  },

  footer: {
    desc: 'Từ tiếng Hàn trước nhập cảnh đến học tiếng, đại học · cao học, việc làm và định cư — nền tảng hành trình du học kết nối bằng CRM và LMS.',
    rights: 'All rights reserved.',
  },
}

export default vi
